package edu.kit.ipd.sdq.eventsim.api;

import org.palladiosimulator.pcm.usagemodel.EntryLevelSystemCall;

/**
 * The system simulation module handles service calls generated by the {@link IWorkload} simulation
 * module.
 * 
 * @author Christoph Föhrdes
 * @author Philipp Merkle
 */
public interface ISystem {

    /**
     * Simulates a system-provided service call by the given user.
     * 
     * @param user
     *            the user issuing the service call
     * @param call
     *            the system service to be called
     * @param onFinishCallback
     *            the callback to be invoked once the system call has been simulated completely
     */
    public void callService(IUser user, EntryLevelSystemCall call, Procedure onFinishCallback);

}
